const withOpacity = (variableName) => `rgb(var(${variableName}) / <alpha-value>)`;

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": withOpacity("--secondary-fixed"),
        "tertiary-container": withOpacity("--tertiary-container"),
        "surface-container-high": withOpacity("--surface-container-high"),
        "on-error-container": withOpacity("--on-error-container"),
        "error": withOpacity("--error"),
        "inverse-surface": withOpacity("--inverse-surface"),
        "outline-variant": withOpacity("--outline-variant"),
        "inverse-on-surface": withOpacity("--inverse-on-surface"),
        "secondary-fixed-dim": withOpacity("--secondary-fixed-dim"),
        "outline": withOpacity("--outline"),
        "on-tertiary": withOpacity("--on-tertiary"),
        "on-background": withOpacity("--on-background"),
        "background": withOpacity("--background"),
        "on-secondary-fixed": withOpacity("--on-secondary-fixed"),
        "surface-container-highest": withOpacity("--surface-container-highest"),
        "surface-container-low": withOpacity("--surface-container-low"),
        "on-primary-container": withOpacity("--on-primary-container"),
        "primary-fixed-dim": withOpacity("--primary-fixed-dim"),
        "on-surface-variant": withOpacity("--on-surface-variant"),
        "primary-container": withOpacity("--primary-container"),
        "on-tertiary-container": withOpacity("--on-tertiary-container"),
        "secondary-container": withOpacity("--secondary-container"),
        "on-tertiary-fixed": withOpacity("--on-tertiary-fixed"),
        "on-secondary-container": withOpacity("--on-secondary-container"),
        "surface-dim": withOpacity("--surface-dim"),
        "surface-container": withOpacity("--surface-container"),
        "on-secondary-fixed-variant": withOpacity("--on-secondary-fixed-variant"),
        "primary-fixed": withOpacity("--primary-fixed"),
        "tertiary-fixed-dim": withOpacity("--tertiary-fixed-dim"),
        "tertiary-fixed": withOpacity("--tertiary-fixed"),
        "primary": withOpacity("--primary"),
        "surface-container-lowest": withOpacity("--surface-container-lowest"),
        "on-primary": withOpacity("--on-primary"),
        "on-error": withOpacity("--on-error"),
        "tertiary": withOpacity("--tertiary"),
        "on-surface": withOpacity("--on-surface"),
        "surface-variant": withOpacity("--surface-variant"),
        "on-primary-fixed": withOpacity("--on-primary-fixed"),
        "on-tertiary-fixed-variant": withOpacity("--on-tertiary-fixed-variant"),
        "on-primary-fixed-variant": withOpacity("--on-primary-fixed-variant"),
        "surface": withOpacity("--surface"),
        "error-container": withOpacity("--error-container"),
        "inverse-primary": withOpacity("--inverse-primary"),
        "surface-tint": withOpacity("--surface-tint"),
        "surface-bright": withOpacity("--surface-bright"),
        "secondary": withOpacity("--secondary"),
        "on-secondary": withOpacity("--on-secondary"),
      },
      fontFamily: {
        "headline": ["var(--font-headline)", "sans-serif"],
        "body": ["var(--font-body)", "sans-serif"],
        "label": ["var(--font-label)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}

