/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#d5e3fd",
        "tertiary-container": "#001e2f",
        "surface-container-high": "#e4e9ed",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "inverse-surface": "#2c3134",
        "outline-variant": "#c6c6cd",
        "inverse-on-surface": "#edf1f5",
        "secondary-fixed-dim": "#b9c7e0",
        "outline": "#76777d",
        "on-tertiary": "#ffffff",
        "on-background": "#171c1f",
        "background": "#f6fafe",
        "on-secondary-fixed": "#0d1c2f",
        "surface-container-highest": "#dfe3e7",
        "surface-container-low": "#f0f4f8",
        "on-primary-container": "#7c839b",
        "primary-fixed-dim": "#bec6e0",
        "on-surface-variant": "#45464d",
        "primary-container": "#131b2e",
        "on-tertiary-container": "#008cc7",
        "secondary-container": "#d5e3fd",
        "on-tertiary-fixed": "#001e2f",
        "on-secondary-container": "#57657b",
        "surface-dim": "#d6dade",
        "surface-container": "#eaeef2",
        "on-secondary-fixed-variant": "#3a485c",
        "primary-fixed": "#dae2fd",
        "tertiary-fixed-dim": "#89ceff",
        "tertiary-fixed": "#c9e6ff",
        "primary": "#000000",
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "tertiary": "#000000",
        "on-surface": "#171c1f",
        "surface-variant": "#dfe3e7",
        "on-primary-fixed": "#131b2e",
        "on-tertiary-fixed-variant": "#004c6e",
        "on-primary-fixed-variant": "#3f465c",
        "surface": "#f6fafe",
        "error-container": "#ffdad6",
        "inverse-primary": "#bec6e0",
        "surface-tint": "#565e74",
        "surface-bright": "#f6fafe",
        "secondary": "#515f74",
        "on-secondary": "#ffffff",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}

